security:
    providers:
        app_user_provider:
            id: App\Domain\Model\Security\UserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_token:
            pattern: ^/api/token$
            security: false
        api:
            pattern: \w+/(edit|delete|publish|create)
            security: true
            stateless: true
            oauth2: true
        api_profile:
            pattern: ^/api/profile
            security: true
            stateless: true
            oauth2: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: ROLE_MODERATOR

    access_control:
        #- { path: ^/blogs, roles: ROLE_USER }
        - { path: ^/\w+/(\w+)-(\w+)-(\w+)-(\w+)-(\w+)/(edit|delete|publish|create), roles: ROLE_USER }
        - { path: ^/\w+/(edit|delete|publish|create), roles: ROLE_USER }
        - { path: ^/profile/my, roles: ROLE_USER }
        - { path: ^/authorize, roles: IS_AUTHENTICATED_REMEMBERED }
        # - { path: ^/profile, roles: ROLE_USER }

    password_hashers:
        App\Domain\Model\Security\User: 'auto'

        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15