version: '3'
services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        depends_on:
            - php-fpm

    node:
        image: node:17-alpine
        user: "1000:1000"
        working_dir: /var/www/frontend
        volumes:
            - ./:/var/www/
        ports:
            - "3000:3000"

    php-fpm:
        build:
            context: ./docker/php
        volumes:
           - ./:/var/www

    postgres:
        image: postgres:14.1-alpine
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: blog
        ports:
            - "54329:5432"

    mailer:
        image: mailhog/mailhog
        ports:
            - "8086:8025"
            - "1025:1025"

    redis:
        image: redis:5.0-alpine
        volumes:
            - redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'



volumes:
    composer:
    postgres:
    redis: