controllers:
    resource: ../src/Application/Controller/*/*
    type: annotation

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

kernel:
    resource: ../src/Kernel.php
    type: annotation

oauth2:
    resource: '@TrikoderOAuth2Bundle/Resources/config/routes.xml'

spa:
    path: /{path}
    methods: GET
    controller: App\Application\Controller\SpaController::main
    requirements:
        path: '.*'